"Setup Chainsaw repositories and rules"

CHAINSAW_PLATFORMS = {
    "darwin_amd64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
    ),
    "darwin_arm64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
    ),
    "linux_386": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:i386",
        ],
    ),
    "linux_amd64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    ),
    "linux_arm64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
    ),
    "linux_ppc64le": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:ppc64le",
        ],
    ),
    "linux_s390x": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:s390x",
        ],
    ),
    "windows_386": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:i386",
        ],
    ),
    "windows_amd64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
    ),
    "windows_arm64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:arm64",
        ],
    ),
}

CHAINSAW_ASSETS = {
    "darwin_amd64": {
        "sha256": "983ce0e4ff32a2112481833d7be4e0a0f0530fadba630fa93d3a635539bc1db0",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.14/chainsaw_darwin_amd64.tar.gz",
    },
    "darwin_arm64": {
        "sha256": "ff806554a15e12faca08b54d373a61e27808f40c34208248924f7b71a301f786",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.14/chainsaw_darwin_arm64.tar.gz",
    },
    "linux_386": {
        "sha256": "deb994d4e176d39c981e39a2f36afe647c73273c441b93d155094bff10b07ff7",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.14/chainsaw_linux_386.tar.gz",
    },
    "linux_amd64": {
        "sha256": "f2f4a3f9a541d65db12f5c910950758f7d56fae20ad5b1272cdc271c9568443e",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.14/chainsaw_linux_amd64.tar.gz",
    },
    "linux_arm64": {
        "sha256": "b6494b71e490ab825890fc12cc575de7f59bfa637d5cfe73c66987e4454e397c",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.14/chainsaw_linux_arm64.tar.gz",
    },
    "linux_ppc64le": {
        "sha256": "c7aa4af8133df4138c3d3c92c9f8cb2ae54aa08ec356c6583722150b678a8c23",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.14/chainsaw_linux_ppc64le.tar.gz",
    },
    "linux_s390x": {
        "sha256": "6087c6e93dd0a9d25c91a4932d4d18b1e32615835794380da7849b3eec3e61a5",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.14/chainsaw_linux_s390x.tar.gz",
    },
    "windows_386": {
        "sha256": "8f4b766541f51703ea6ed40890ff9dda099d464e0f5f18667f28704aa8b00ae6",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.14/chainsaw_windows_386.tar.gz",
    },
    "windows_amd64": {
        "sha256": "ec037c11fba6a971d986153f2c35b98db04f878ee9b3e112bb105b4aca9fff60",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.14/chainsaw_windows_amd64.tar.gz",
    },
    "windows_arm64": {
        "sha256": "ab91d495f12f9895b6c66eef18fb2cf3229a90b49fdcb144adfb2a2af9300c3d",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.14/chainsaw_windows_arm64.tar.gz",
    },
}

def _chainsaw_toolchains_repo_impl(rctx):
    build = ""

    for [platform, meta] in CHAINSAW_PLATFORMS.items():
        build += """
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:chainsaw_toolchain",
    toolchain_type = "@io_github_janhicken_rules_kubebuilder//kubebuilder:chainsaw_toolchain",
)
""".format(
            platform = platform,
            user_repository_name = rctx.attr.user_repository_name,
            compatible_with = meta.compatible_with,
        )

    # Base BUILD file for this repository
    rctx.file("BUILD", build)

chainsaw_toolchains_repo = repository_rule(
    _chainsaw_toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "user_repository_name": attr.string(doc = "Base name for toolchains repository"),
    },
)

def _chainsaw_platform_repo_impl(rctx):
    asset = CHAINSAW_ASSETS[rctx.attr.platform]

    rctx.download_and_extract(
        url = asset["url"],
        sha256 = asset["sha256"],
    )
    build = """# @generated by @io_github_janhicken_rules_kubebuilder//kubebuilder/private:chainsaw_toolchain.bzl
load("@io_github_janhicken_rules_kubebuilder//kubebuilder:toolchain.bzl", "chainsaw_toolchain")
exports_files(["chainsaw"])
chainsaw_toolchain(
    name = "chainsaw_toolchain",
    bin = "chainsaw",
    visibility = ["//visibility:public"],
)
"""

    # Base BUILD file for this repository
    rctx.file("BUILD", build)

chainsaw_platform_repo = repository_rule(
    implementation = _chainsaw_platform_repo_impl,
    doc = "Fetch external tools needed for the Chainsaw toolchain",
    attrs = {
        "platform": attr.string(mandatory = True, values = CHAINSAW_PLATFORMS.keys()),
    },
)
