"Setup Chainsaw repositories and rules"

CHAINSAW_PLATFORMS = {
    "darwin_amd64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
    ),
    "darwin_arm64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
    ),
    "linux_386": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:i386",
        ],
    ),
    "linux_amd64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    ),
    "linux_arm64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
    ),
    "linux_ppc64le": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:ppc64le",
        ],
    ),
    "linux_s390x": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:s390x",
        ],
    ),
    "windows_386": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:i386",
        ],
    ),
    "windows_amd64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
    ),
    "windows_arm64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:arm64",
        ],
    ),
}

CHAINSAW_ASSETS = {
    "darwin_amd64": {
        "sha256": "ddb56002ff8c6265f55ec40c82eb0ef0dddec5127dd12d4fc5e7953453481f4b",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.15/chainsaw_darwin_amd64.tar.gz",
    },
    "darwin_arm64": {
        "sha256": "502bef17dd822217e82590e9ccf01c1e26a56b3fa34a835789b9af73e82a169a",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.15/chainsaw_darwin_arm64.tar.gz",
    },
    "linux_386": {
        "sha256": "50c27d859c7f4624e53560af3f8e1a53c3ceb961755f3876ef497569cb5f097c",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.15/chainsaw_linux_386.tar.gz",
    },
    "linux_amd64": {
        "sha256": "295d226c89f126c0a97775d364be149f47a810c8a3f9829ee410583d0c1abe3c",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.15/chainsaw_linux_amd64.tar.gz",
    },
    "linux_arm64": {
        "sha256": "fecf5f3ea74d11da2cd5d95a4c016d5d2543cbc4844ce21adf5e727e7ffd9e44",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.15/chainsaw_linux_arm64.tar.gz",
    },
    "linux_ppc64le": {
        "sha256": "6f3164ac567ec59a4e529af8f10e03bbf7442b71918ec85666e4533355a272c7",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.15/chainsaw_linux_ppc64le.tar.gz",
    },
    "linux_s390x": {
        "sha256": "29d7985b510f3f96396b795b2681e60bc27ff68baf6c38aafeb12eaa61d74021",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.15/chainsaw_linux_s390x.tar.gz",
    },
    "windows_386": {
        "sha256": "05c679f655d8d74a2a7cf69e8fb618bc6111f930379783bc8265cacde7465ba7",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.15/chainsaw_windows_386.tar.gz",
    },
    "windows_amd64": {
        "sha256": "02e7d519c4e815c89dc8a4b14e2b70474d5301f514e721c0e5b3062f67294229",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.15/chainsaw_windows_amd64.tar.gz",
    },
    "windows_arm64": {
        "sha256": "d580cbfc17fc5fc3cd7fbdaf5ab6246dcbe33799f2a79284af8eb6ebdb861b8a",
        "url": "https://github.com/kyverno/chainsaw/releases/download/v0.2.15/chainsaw_windows_arm64.tar.gz",
    },
}

def _chainsaw_toolchains_repo_impl(rctx):
    build = ""

    for [platform, meta] in CHAINSAW_PLATFORMS.items():
        build += """
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:chainsaw_toolchain",
    toolchain_type = "@io_github_janhicken_rules_kubebuilder//kubebuilder:chainsaw_toolchain",
)
""".format(
            platform = platform,
            user_repository_name = rctx.attr.user_repository_name,
            compatible_with = meta.compatible_with,
        )

    # Base BUILD file for this repository
    rctx.file("BUILD", build)

chainsaw_toolchains_repo = repository_rule(
    _chainsaw_toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "user_repository_name": attr.string(doc = "Base name for toolchains repository"),
    },
)

def _chainsaw_platform_repo_impl(rctx):
    asset = CHAINSAW_ASSETS[rctx.attr.platform]

    rctx.download_and_extract(
        url = asset["url"],
        sha256 = asset["sha256"],
    )
    build = """# @generated by @io_github_janhicken_rules_kubebuilder//kubebuilder/private:chainsaw_toolchain.bzl
load("@io_github_janhicken_rules_kubebuilder//kubebuilder:toolchain.bzl", "chainsaw_toolchain")
exports_files(["chainsaw"])
chainsaw_toolchain(
    name = "chainsaw_toolchain",
    bin = "chainsaw",
    visibility = ["//visibility:public"],
)
"""

    # Base BUILD file for this repository
    rctx.file("BUILD", build)

chainsaw_platform_repo = repository_rule(
    implementation = _chainsaw_platform_repo_impl,
    doc = "Fetch external tools needed for the Chainsaw toolchain",
    attrs = {
        "platform": attr.string(mandatory = True, values = CHAINSAW_PLATFORMS.keys()),
    },
)
