"Setup controller-gen repositories and rules"

CONTROLLER_GEN_PLATFORMS = {
    "darwin-amd64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
    ),
    "darwin-arm64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
    ),
    "linux-amd64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    ),
    "linux-arm64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
    ),
    "linux-ppc64le": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:ppc",
        ],
    ),
    "linux-s390x": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:s390x",
        ],
    ),
    "windows-amd64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
    ),
}

KUBERNETES_VERSION_MAPPING = {
    "1.33": "0.18.0",
    "1.34": "0.19.0",
    "1.35": "0.20.1",
    "1.36": "0.21.0",
}

CONTROLLER_GEN_VERSIONS = {
    "0.18.0": {
        "darwin-amd64": "sha384-bVVHwzMOh+lrzMpteNYSBV7Mq5MSYSPQ4M2j/adLV0rVxkqVV/nhpAvV48aQVS6V",
        "darwin-arm64": "sha384-Gjfse8ifYVHoqYIwh+OmQXN/KdOjQHr3O0e6gfgIBQXB50OtZntEs7JSHDLDReRj",
        "linux-amd64": "sha384-jMZzGpPYGU55fclPofAqHxyd37yXFAB4u5S/7yiH6VuBwFY22nMFY7kqfnsDoLXv",
        "linux-arm64": "sha384-NiC4boKh0iY8nFqIUdLpSJY4qwN5dXmWSPVWeMF2UJmj3HHGRA8fUnnjiZVQoTDT",
        "linux-ppc64le": "sha384-95LDfZKmZfmZK6pGYkC3aWTAVhk7PStDdAQrHcZTV6zivu9tdozOTmvQDOEtgZq/",
        "linux-s390x": "sha384-qA0zRT0NRmO6N8HhzTxbmTvx/t9SOCoIpxyalYKXIk1zvYFd8br8mJyUJ2XEbbRv",
        "windows-amd64": "sha384-NSGhVYQnN+BdgzvodcWr5fFmMfGUQdotb+4Xxexn8L1P2JJvTMKczLXIWT9ZdEDJ",
    },
    "0.19.0": {
        "darwin-amd64": "sha384-RWp3N0j++AFWbkpocYTXAIcvcFZ4M52rJNrGytiL5UKuSqyxmIiszxnHvJrKX/np",
        "darwin-arm64": "sha384-iQSDVVU9iiUeDlW1E0gi+EweyZKcCXVO3ABkmvpn7GLRPTmqwMEHILl6eLrwAoA6",
        "linux-amd64": "sha384-PmbZLpovXiraxmmokhNoZ9XITn2eYqSs2u8erFzq4eX8BJsA+QbBaETREuYP+15+",
        "linux-arm64": "sha384-GlPisQ9VwsIdZ4hqLSjl+fMRTJm+faUPgTWyyTPa5DNg7nCL1rDDVORn2/esluqG",
        "linux-ppc64le": "sha384-r50zeAnuCqCB8VgGy7i0LtxxzTSgNlA9lsayxcmNIV+5LMnuP3gqt9TgBHVxw0vz",
        "linux-s390x": "sha384-vj0KJQB16WsN/FcP9zyX8ucIzus8atuv2jRGnVD7a48BukGzfXMoxtHkF6QiYZBN",
        "windows-amd64": "sha384-J6ZjXXWtWleEGCokfJc9/JuaDNK/eMdkzeK/rQWvxYqxvwrTjJoBoPjmT3nl0w8C",
    },
    "0.20.1": {
        "darwin-amd64": "sha384-rDXgY8UfdeqJy+k0Kh83urGNHohi92Apj7TrzYSqmxlYp7TnDhT+qq7cgk418v1n",
        "darwin-arm64": "sha384-MId/MpDmEHcjtLoNFVTrOVfScnNaSsjUa9BevccV/0BEw+QoA1ORf/rySDoC0YEq",
        "linux-amd64": "sha384-9VpHbjQCMaawHQkLsJcN4K0NKjfRmabIz7ZJuAp3cbiqQJYE2l9hsD4AjUJ40Xgs",
        "linux-arm64": "sha384-sZcpsXQSZvgb2C0f3d6EIe/G0AtnLZtS9Ewz35XA0+hRhzh1keuuScxba84H52gD",
        "linux-ppc64le": "sha384-K9tZLA1zhjEL0O7LFnkByid9Ws2qpB3teBn9oDN1qJv03v0b49WQ9VdO6SYXWjzQ",
        "linux-s390x": "sha384-ee7FTawinmX3cDOlTgObJAvCYiXsCXOfL0GzHLagevqefy1oT0NgyvmoQ49GYfTn",
        "windows-amd64": "sha384-1qjr+I9W6/c6JOUriXmfFPpc1OrPGWHcsmOfrfD7Br28V/IhH+CnhhOpQVR5VEvQ",
    },
    "0.21.0": {
        "darwin-amd64": "sha384-9ScRvYtdRGACYtQdDpo+XY/Wl1NYhOpstGGG1zsMoGdf/Ub/PIjhmiJz0rL6Nmwe",
        "darwin-arm64": "sha384-r3YBBSVbkoXkhEn5eE0G3GxgUbVoQhyUroIRcWLKtNYEYB7BRq9s32FI7T8hVsZ5",
        "linux-amd64": "sha384-91jFvzCKe+v6mgjTVnbhGLE9pSf4pRNX0R/dxeOsMNlDY/PpjUzv/ic4ZVCzg5vu",
        "linux-arm64": "sha384-Melw1bG/06BGHk17UXHcAokxBvsRXX7qQnUlOqcx1RBHZtJ4q6ybKI6zLTqzxBL/",
        "linux-ppc64le": "sha384-SeeeojOjp8GwJbjH1OfZjhoWT8YL+TvFG82k/VxZY9EAY7d0Ekqu0DH6bUQ8NRoB",
        "linux-s390x": "sha384-WeDOzS+QhJNaWGrTlZoaV94BGwN/2eDO5PKL0YZMg3bqEsqNEmVe23rNCjAErQ2a",
        "windows-amd64": "sha384-qZrMnIauwz35aizcvB/Iwj+f9ctSI7yYQtBQQqthAULC/LD5aVHI0PLT/2eQZut7",
    },
}

def _controller_gen_toolchains_repo_impl(rctx):
    # Expose a concrete toolchain which is the result of Bazel resolving the toolchain
    # for the execution or target platform.
    # Workaround for https://github.com/bazelbuild/bazel/issues/14009
    defs_bzl = """# @generated by @io_github_janhicken_rules_kubebuilder//kubebuilder/private:controller_gen_toolchain.bzl

# Forward all the providers
def _resolved_toolchain_impl(ctx):
    toolchain_info = ctx.toolchains["@io_github_janhicken_rules_kubebuilder//kubebuilder:controller_gen_toolchain"]
    return [
        toolchain_info,
        toolchain_info.default,
        toolchain_info.controller_gen,
        toolchain_info.template_variables,
    ]

# Copied from java_toolchain_alias
# https://cs.opensource.google/bazel/bazel/+/master:tools/jdk/java_toolchain_alias.bzl
resolved_toolchain = rule(
    implementation = _resolved_toolchain_impl,
    toolchains = ["@io_github_janhicken_rules_kubebuilder//kubebuilder:controller_gen_toolchain"],
)
"""
    rctx.file("defs.bzl", defs_bzl)

    build = """# @generated by @io_github_janhicken_rules_kubebuilder//kubebuilder/private:controller_gen_toolchain.bzl
#
# These can be registered in the workspace file or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the controller_gen_register_toolchains macro
# so you don't normally need to interact with these targets.

load(":defs.bzl", "resolved_toolchain")

resolved_toolchain(name = "resolved_toolchain", visibility = ["//visibility:public"])

"""

    for [platform, meta] in CONTROLLER_GEN_PLATFORMS.items():
        build += """
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:controller_gen_toolchain",
    toolchain_type = "@io_github_janhicken_rules_kubebuilder//kubebuilder:controller_gen_toolchain",
)
""".format(
            platform = platform,
            user_repository_name = rctx.attr.user_repository_name,
            compatible_with = meta.compatible_with,
        )

    # Base BUILD file for this repository
    rctx.file("BUILD", build)

controller_gen_toolchains_repo = repository_rule(
    _controller_gen_toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "user_repository_name": attr.string(doc = "Base name for toolchains repository"),
    },
)

def _controller_gen_platform_repo_impl(rctx):
    ext = ".exe" if "windows" in rctx.attr.platform else ""

    # https://github.com/kubernetes-sigs/controller-tools/releases/download/v0.17.2/controller-gen-darwin-arm64
    url = "https://github.com/kubernetes-sigs/controller-tools/releases/download/v{0}/controller-gen-{1}{2}".format(
        rctx.attr.version,
        rctx.attr.platform,
        ext,
    )

    rctx.download(
        url = url,
        output = "controller-gen" + ext,
        executable = True,
        integrity = CONTROLLER_GEN_VERSIONS[rctx.attr.version][rctx.attr.platform],
    )
    build = """# @generated by @io_github_janhicken_rules_kubebuilder//kubebuilder/private:controller_gen_toolchain.bzl
load("@io_github_janhicken_rules_kubebuilder//kubebuilder:toolchain.bzl", "controller_gen_toolchain")
exports_files(["{0}"])
controller_gen_toolchain(name = "controller_gen_toolchain", bin = "{0}", visibility = ["//visibility:public"])
""".format("controller-gen" + ext)

    # Base BUILD file for this repository
    rctx.file("BUILD", build)

controller_gen_platform_repo = repository_rule(
    implementation = _controller_gen_platform_repo_impl,
    doc = "Fetch external tools needed for controller_gen toolchain",
    attrs = {
        "platform": attr.string(mandatory = True, values = CONTROLLER_GEN_PLATFORMS.keys()),
        "version": attr.string(mandatory = True, values = CONTROLLER_GEN_VERSIONS.keys()),
    },
)
