apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project-system
  name: project-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never

