# Cut a release whenever a new tag is pushed to the repo.
name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    name: Release
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.3
    with:
      release_files: rules_kubebuilder-*.tar.gz
      prerelease: false
    permissions:
      contents: write
  publish:
    name: Publish to BCR
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.0.0
    with:
      tag_name: ${{ github.ref_name }}
      registry_fork: janhicken/bazel-central-registry
      attest: false
    permissions:
      attestations: write
      contents: write
      id-token: write
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
